// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddHighlight(arg1:main.Highlight):Promise<main.Highlight>;

export function ChooseSaveDir():Promise<string>;

export function DeleteHighlight(arg1:number):Promise<void>;

export function ExportHighlights():Promise<main.HighlightsExport>;

export function GetConfig():Promise<main.Config>;

export function Highlights():Promise<Array<main.Highlight>>;

export function Labels():Promise<Array<main.Count>>;

export function List(arg1:main.Query):Promise<Array<main.Msg>>;

export function Open(arg1:number):Promise<main.Issue>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveEmail(arg1:number,arg2:string):Promise<string>;

export function Senders(arg1:string):Promise<Array<main.Count>>;

export function ServerLabels():Promise<Array<string>>;

export function SetAppearance(arg1:string,arg2:number):Promise<void>;

export function SetHidden(arg1:number,arg2:boolean):Promise<void>;

export function SetNote(arg1:number,arg2:string):Promise<void>;

export function SetRead(arg1:number,arg2:boolean):Promise<void>;

export function Sync():Promise<void>;
