// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHighlight(arg1) {
  return window['go']['main']['App']['AddHighlight'](arg1);
}

export function ChooseSaveDir() {
  return window['go']['main']['App']['ChooseSaveDir']();
}

export function DeleteHighlight(arg1) {
  return window['go']['main']['App']['DeleteHighlight'](arg1);
}

export function ExportHighlights() {
  return window['go']['main']['App']['ExportHighlights']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Highlights() {
  return window['go']['main']['App']['Highlights']();
}

export function Labels() {
  return window['go']['main']['App']['Labels']();
}

export function List(arg1) {
  return window['go']['main']['App']['List'](arg1);
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveEmail(arg1, arg2) {
  return window['go']['main']['App']['SaveEmail'](arg1, arg2);
}

export function Senders(arg1) {
  return window['go']['main']['App']['Senders'](arg1);
}

export function ServerLabels() {
  return window['go']['main']['App']['ServerLabels']();
}

export function SetAppearance(arg1, arg2) {
  return window['go']['main']['App']['SetAppearance'](arg1, arg2);
}

export function SetHidden(arg1, arg2) {
  return window['go']['main']['App']['SetHidden'](arg1, arg2);
}

export function SetNote(arg1, arg2) {
  return window['go']['main']['App']['SetNote'](arg1, arg2);
}

export function SetRead(arg1, arg2) {
  return window['go']['main']['App']['SetRead'](arg1, arg2);
}

export function Sync() {
  return window['go']['main']['App']['Sync']();
}
